version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    container_name: chattea-frontend
    networks:
      - react-net
    volumes:
      - ./src:/usr/app/src
      - .env:/usr/app/.env
networks:
  react-net:
    driver: bridge